### auth
POST {{METABASE_HOST}}/api/session
Content-Type: application/json

{
  "username": "{{METABASE_USERNAME}}",
  "password": "{{METABASE_PASSWORD}}"
}

### metabase settings
GET {{METABASE_HOST}}/api/setting


### metabase groups
GET {{METABASE_HOST}}/api/permissions/group

### metabase get group
GET {{METABASE_HOST}}/api/permissions/group/:id

### update metabase group name
PUT {{METABASE_HOST}}/api/permissions/group/:id
Content-Type: application/json

{
  "name": "some name"
}