### auth
POST {{metabase.host}}/api/session
Content-Type: application/json

{
  "username": "{{metabase.username}}",
  "password": "{{metabase.password}}"
}

### metabase settings
GET {{metabase.host}}/api/setting
