### auth
POST {{METABASE_HOST}}/api/session
Content-Type: application/json

{
  "username": "{{METABASE_USERNAME}}",
  "password": "{{METABASE_PASSWORD}}"
}

### metabase settings
GET {{METABASE_HOST}}/api/setting

### metabase groups
GET {{METABASE_HOST}}/api/permissions/group

### metabase get group
@groupId = 1
GET {{METABASE_HOST}}/api/permissions/group/{{groupId}}

### update metabase group name
PUT {{METABASE_HOST}}/api/permissions/group/{{groupId}}
Content-Type: application/json

{
  "name": "some name"
}


### metabase get card
@databaseId = 2
GET {{METABASE_HOST}}/api/database/{{databaseId}}

### metabase get card
@cardId = 141
GET {{METABASE_HOST}}/api/card/{{cardId}}

### metabase get dashboard
@dashboardId = 27
GET {{METABASE_HOST}}/api/dashboard/{{dashboardId}}

### metabase get dashboard
@queryId = 1
GET {{METABASE_HOST}}/api/query/{{queryId}}



### metabase get user
@userId = 4
GET {{METABASE_HOST}}/api/user/{{userId}}

### metabase get field
@fieldId = 585
GET {{METABASE_HOST}}/api/field/{{fieldId}}

### metabase get field
@tableId = 24
GET {{METABASE_HOST}}/api/table/{{tableId}}
